FROM node:16.17.0-alpine
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY server ./server
RUN ls -a
RUN npm install
RUN npm run build
RUN ls -a
## this is stage two , where the app actually runs
FROM node:16.17.0-alpine
WORKDIR /usr
COPY package.json ./
RUN npm install --only=production
COPY --from=0 /usr/server .
RUN npm install pm2 -g
EXPOSE 80
CMD ["pm2-runtime","server.js"]